version: "3.9"

services:
  # these are the recommended settings to run your app
  hyperchalk:
    build:
        context: .
        dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "8342:8342"
    volumes:
      - data_infoboard:/srv/data
      - media_infoboard:/srv/media
      - static_infoboard:/srv/static_copy
      # use this if you want to create your own config file instead of using the environment vars
      # - ./deployment_settings.py:/srv/deployment_settings.py:ro
    command: [ "draw.asgi", "--bind=0.0.0.0:8342", "--workers=4" ]
    environment:
      # use this if you want to create your own config file instead of using the environment vars
      # DJANGO_SETTINGS_MODULE: "deployment_settings"

      # these three settings make this compose file compatible with hyperchalk.
      # TODO: change the mariadb password to your own!
      DJANGO_SETTINGS_MODULE: "draw.env_settings"
      HC_ADMIN_NAM: "admin name"
      HC_ADMIN_MAIL: "admin email"
      HC_ALLOW_AUTOMATIC_ROOM_CREATION: False
      HC_SHOW_CREATE_ROOM_PAGE: False
      HC_ALLOW_ANONYMOUS_VISITS: False
      HC_PUBLIC_ROOMS: "[]"
      HC_ENABLE_TRACKING_BY_DEFAULT: True
      HC_DEBUG: True
      HC_SERVE_FILES: True
      HC_SECRET_KEY: "secret"
      HC_ALLOWED_HOSTS: "*"
      HC_LINK_BASE: "http://localhost:8342"
      HC_TIME_ZONE: "Europe/Warsaw"
      HC_LANGUAGE_CODE: "pl-PL"
      HC_GOOGLE_OAUTH2_KEY: "token"
      HC_GOOGLE_OAUTH2_SECRET: "token"

    depends_on:
      - maria
      - redis

  maria:
    image: mariadb:latest
    environment:
      MARIADB_DATABASE: hyperchalk
      MARIADB_ROOT_PASSWORD: CHANGE_THIS_PASSWORD
      MARIADB_USER: hyperchalk

    volumes:
      - db_infoboard:/var/lib/mysql

  redis:
    image: redis:alpine
    volumes:
      - redis_infoboard_data:/data
      - redis_infoboard_conf:/usr/local/etc/redis/redis.conf:ro

volumes:
  redis_infoboard_data:
  redis_infoboard_conf:
  media_infoboard:
  static_infoboard:
  db_infoboard:
  data_infoboard:
