# Generated by Django 4.2.19 on 2025-07-23 10:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collab', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardgroups',
            name='users_that_can_draw',
            field=models.ManyToManyField(blank=True, related_name='drawing_users_group', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='excalidrawroom',
            name='user_room_name',
            field=models.CharField(default='sOg4lZ5Xn9oSJbcBu', max_length=24),
        ),
    ]
