# Generated by Django 4.2.19 on 2025-02-23 22:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collab', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardgroups',
            name='class_year',
            field=models.IntegerField(default=2025, validators=[django.core.validators.MinLengthValidator(4), django.core.validators.MaxLengthValidator(4)]),
        ),
        migrations.AlterField(
            model_name='boardgroups',
            name='code',
            field=models.CharField(default='', editable=False, max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='excalidrawroom',
            name='user_room_name',
            field=models.CharField(default='j192cSMQ08asIbV7j', max_length=24),
        ),
    ]
