# Generated by Django 4.2.19 on 2025-02-22 20:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('collab', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='excalidrawroom',
            name='user_room_name',
            field=models.CharField(default='O5m5g58zHnJVLgsuuAzQ4VoN', max_length=64),
        ),
        migrations.AlterField(
            model_name='excalidrawlogrecord',
            name='room_name',
            field=models.UUIDField(),
        ),
        migrations.AlterField(
            model_name='excalidrawroom',
            name='room_name',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
