# Generated by Django 4.2.19 on 2025-07-23 11:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collab', '0002_boardgroups_users_that_can_draw_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='excalidrawroom',
            name='users_that_can_draw',
            field=models.ManyToManyField(blank=True, related_name='drawing_users_in_table', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='excalidrawroom',
            name='user_room_name',
            field=models.CharField(default='TNd3VRCwEov1nDkqr', max_length=24),
        ),
    ]
