# Generated by Django 4.2.19 on 2025-02-22 23:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collab', '0002_excalidrawroom_user_room_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='excalidrawroom',
            name='user_room_name',
            field=models.CharField(default='0oliGkE4NeliM2mQe', max_length=24),
        ),
        migrations.CreateModel(
            name='BoardGroups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('boards', models.ManyToManyField(related_name='boards', to='collab.excalidrawroom')),
                ('users', models.ManyToManyField(related_name='users_group', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
