# Generated by Django 4.2.19 on 2025-02-24 10:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collab', '0002_alter_boardgroups_class_year_alter_boardgroups_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_creator',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='boardgroups',
            name='boards',
            field=models.ManyToManyField(blank=True, related_name='boards', to='collab.excalidrawroom'),
        ),
        migrations.AlterField(
            model_name='boardgroups',
            name='category',
            field=models.CharField(choices=[('podstawowy', 'podstawowy'), ('średnio-zaawansowany', 'średnio-zaawansowany'), ('zaawansowany', 'zaawansowany')], default='podstawowa', max_length=50),
        ),
        migrations.AlterField(
            model_name='boardgroups',
            name='class_year',
            field=models.IntegerField(default=2025),
        ),
        migrations.AlterField(
            model_name='boardgroups',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='users_group', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='excalidrawroom',
            name='user_room_name',
            field=models.CharField(default='Pj92J9g2gB2KVrjTU', max_length=24),
        ),
    ]
