# Generated by Django 4.2.19 on 2025-02-23 00:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collab', '0003_alter_excalidrawroom_user_room_name_boardgroups'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardgroups',
            name='owner',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='owner_group', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='excalidrawroom',
            name='user_room_name',
            field=models.CharField(default='ouXQoeIlM5588FmOc', max_length=24),
        ),
    ]
