# Generated by Django 4.2.19 on 2025-11-18 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collab', '0003_excalidrawroom_users_that_can_draw_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='excalidrawroom',
            name='user_room_name',
            field=models.CharField(default='M2MzdG3hfZgz9ZIJD6Lm00KCFVb76WKJIEeufS9rhn0UYCJ2zn', max_length=50),
        ),
    ]
