# Generated by Django 4.2.19 on 2025-02-26 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collab', '0003_customuser_is_creator_alter_boardgroups_boards_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile_image',
            field=models.ImageField(default='profile_images/default.png', upload_to='profile_images', verbose_name='Zdjęcie profilowe'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_creator',
            field=models.BooleanField(default=False, help_text='Użytkownik, który utworzył pokój', verbose_name='Twórca'),
        ),
        migrations.AlterField(
            model_name='excalidrawroom',
            name='user_room_name',
            field=models.CharField(default='6CD2eCC5lGCSYnwb9', max_length=24),
        ),
    ]
