name: Build and Push Docker Image

on:
  push:
    branches:
      - main
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      # Jeśli push pochodzi z tagu, IMAGE_TAG przyjmie wartość nazwy tagu,
      # w przeciwnym przypadku zostanie ustawione na "main"
      IMAGE_TAG: ${{ github.ref_type == 'tag' && github.ref_name || 'main' }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set lowercase repository variable
        run: echo "REPO=$(echo $GITHUB_REPOSITORY | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ env.REPO }}:${{ env.IMAGE_TAG }}
            ghcr.io/${{ env.REPO }}:latest
